version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seriesdb
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/seriesdb?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db
